#!/bin/bash

#Checking for config files
CONFIG=$(ls -A /etc/bareos)
MYSQL=$(ls -A /db)

if [ "$CONFIG" = "" ];then
	tar -xzvf /opt/bareos-etc-dir.tgz -C /
fi


if [ "$MYSQL" = "" ];then
	tar -xzvf /opt/db.tgz -C /db	
fi


#Fixing Bareos Permissions
chown -R bareos.bareos /etc/bareos


#Not running until mysql gets ready 
echo "Checking Configuration and Database connection ... "
su -s /bin/sh bareos -c "/usr/sbin/bareos-dir -f -t" 
	

#Main Process
exec /usr/sbin/bareos-dir -f -d 10 -g bareos -u bareos -c /etc/bareos